name: Tests
on: [push, pull_request]
permissions:
  contents: read
env:
  CC: "clang"
  CG_LDFLAGS: "-fuse-ld=mold"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ["", "stable"]

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          go-version-file: "go.mod"

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends clang mold libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev

      - name: Tests
        run: go test -race ./...
