name: Tests
on: [push, pull_request]
permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.19.x', 'stable']

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: WillAbides/setup-go-faster@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends clang libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev

    - name: Tests
      run: go test ./...
